### ISSUE TITLE
Find a way to redefine \or

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/texvc-latex#2]
MediaWiki redefines `\or` as `\lor`. See the [help page](https://en.wikipedia.org/wiki/Help:Displaying_a_formula#Logic).
So many formulae in Wikipedia use the `\or`-command.
The intended use of this package is to

>  Provide Me­di­aWiki LaTeX com­mands in a regular LaTeX environment, so that users can copy and past for­mu­lae from Me­di­aWiki to LaTeX doc­u­ments.

As of today a user that copies a formula from wikipedia that contains an `\or` command will get a (probably confusing) error message. 

To solve this issue, we should find a proper workaround so that formulae which include \or can be copied from Wikipedia to LaTeX. 

I tried \newcommand{\or} which did not work as expected.

PS: I should also improve the description on [ctan](https://www.ctan.org/pkg/texvc)

**Comment by HowardCohl** [comment]
@physikerwelt You need to explain this much better than you did, please.

**Comment by physikerwelt** [comment]
@HowardCohl I updated the description above.

**Comment by HowardCohl** [comment]
Thank you. 

On the texvc help page there are many different ways to referring to texvc, such as TexVC, and Texvc. texvc should probably be consistently written.
